apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffsa667
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffsa667
  template:
    metadata:
      labels:
        app: ffsa667
    spec:
      containers:
      - image: okteto.dev/ffsa667:latest
        name: ffsa667
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d4a98401-00d9-4bd5-92c4-e644d752b6e0"
        - name: Vless_Path
          value: "/vl5saqs55"
        - name: Vmess_UUID
          value: "d4a98401-00d9-4bd5-92c4-e644d752b6e0"
        - name: Vmess_Path
          value: "/vffdq2m666"
        - name: Share_Path
          value: "/v2link"
